## Done to increase the memory available to Gradle.
#org.gradle.jvmargs=-Xmx2G
#org.gradle.parallel=true
## Mod properties
#mod_version=2.2.6
#maven_group=dev.mineland
#archives_name=item-interactions-mod
#enabled_platforms=fabric,neoforge
## Minecraft properties
#minecraft_version=1.21.11
## Dependencies
#
## Fabric
#fabric_loader_version=0.18.1
#fabric_api_version=0.140.2+1.21.11
#modmenu_version=14.0.0-rc.2
#
## Neo
#neoforge_version=21.11.17-beta
#
## Mod's version range as a string here
##version_range_fabric=>=1.21.9 <=1.21.10
#version_range_fabric=>=1.21.11
#version_range_neo=[1.21.11]
#

# Project
version=2.2.7
group=dev.mineland
java_version=21

# Common
minecraft_version=1.21.11
mod_name=Item interactions mod
mod_author=mineland
mod_id=item_interactions_mod
license=LGPL-3.0
credits=
description=Item interactions in your inventory!
github=https://github.com/mineland-2048/item_interactions_mod
#
#minecraft_version_range=[26.1, 26.2)
minecraft_version_range=[1.21.11, 1.21.12)


## This is the version of minecraft that the 'common' project uses, you can find a list of all versions here
## https://projects.neoforged.net/neoforged/neoform
#neo_form_version=26.1-1
neo_form_version=1.21.11-20251209.172050

# Fabric, see https://fabricmc.net/develop/ for new versions
fabric_version=0.141.3+1.21.11
fabric_loader_version=0.18.4
modmenu_version=14.0.0-rc.2

# NeoForge, see https://projects.neoforged.net/neoforged/neoforge for new versions
#neoforge_version=26.1.0.1-beta
neoforge_version=21.11.3-beta
neoforge_loader_version_range=[4,)

parchment_minecraft=1.21.11
parchment_version=2025.12.20

# Mod's version range as a string here
#version_range_fabric=>=1.21.9 <=1.21.10
version_range_fabric=>=1.21.11
version_range_neo=[1.21.11]

# Gradle
org.gradle.daemon=false