## Done to increase the memory available to Gradle.
#org.gradle.jvmargs=-Xmx2G
#org.gradle.parallel=true
## Mod properties
#mod_version=2.2.6
#maven_group=dev.mineland
#archives_name=item-interactions-mod
#enabled_platforms=fabric,neoforge
## Minecraft properties
#minecraft_version=1.21.11
## Dependencies
#
## Fabric
#fabric_loader_version=0.18.1
#fabric_api_version=0.140.2+1.21.11
#modmenu_version=14.0.0-rc.2
#
## Neo
#neoforge_version=21.11.17-beta
#
## Mod's version range as a string here
##version_range_fabric=>=1.21.9 <=1.21.10
#version_range_fabric=>=1.21.11
#version_range_neo=[1.21.11]
#

# Project

# Common
mod.name=Item interactions mod
mod.id=item_interactions_mod
mod.group=dev.mineland
mod.version=2.2.7
mod.author=mineland
mod.description=Item interactions in your inventory!
mod.license=LGPL-3.0
mod.github=https://github.com/mineland-2048/item_interactions_mod
#credits=
#

# Stonecutter
stonecutter_enabled_platforms=fabric, neoforge
stonecutter_enabled_common_versions=1.21.11
stonecutter_enabled_fabric_versions=1.21.11
stonecutter_enabled_forge_versions=
stonecutter_enabled_neoforge_versions=1.21.11


# Individual settings modified per node

java.version=
minecraft_version=
min_minecraft_version=

#parchment_minecraft=
#parchment_version=
deps.parchment=
# Fabric, see https://fabricmc.net/develop/ for new versions
deps.fabric-loader=
deps.fabric-api=
deps.modmenu=
deps.flow=2.2.0+1.21
deps.tia=1.2.3-fabric
#modmenu_version=14.0.0-rc.2

#minecraft_version_range=[26.1, 26.2)
#minecraft_version_range=[1.21.11, 1.21.12)


## This is the version of minecraft that the 'common' project uses, you can find a list of all versions here
## https://projects.neoforged.net/neoforged/neoform
#neo_form_version=26.1-1

# 1.21.11-20251209.172050
#neo_form_version=


# NeoForge, see https://projects.neoforged.net/neoforged/neoforge for new versions
#neoforge_version=26.1.0.1-beta
deps.neoforge=
neoforge_loader_version_range=[4,)


# Mod's version range as a string here
#version_range_fabric=>=1.21.9 <=1.21.10
#version_range_fabric=>=1.21.11
version_range_fabric=
#version_range_neo=[1.21.11]
version_range_neo=

# Gradle
org.gradle.daemon=false