# Stonecutter
stonecutter_enabled_platforms=fabric, neoforge

# Java
java.version=25

# Minecraft
minecraft_version=26.1
min_minecraft_version=26.1

# Mappings

parchment_minecraft=
parchment_version=


# Fabric
deps.fabric-loader=0.18.5
deps.fabric-api=0.144.3

# NeoForge
deps.neoforge=26.1.0.7-beta
neoforge_loader_version_range=[4,)

# Dependencies
deps.modmenu=18.0.0-alpha.8
deps.flow=2.2.0+1.21
deps.tia=1.2.3-fabric
# TODO: add TIA, Flow and whatever else that has fixes


