# Stonecutter
stonecutter_enabled_platforms=fabric, neoforge

# Java
java.version=21

# Minecraft
minecraft_version=1.21.11
min_minecraft_version=1.21.11

# Mappings

parchment_minecraft=1.21.11
parchment_version=2025.12.20


# Fabric
deps.fabric-loader=0.18.4
deps.fabric-api=0.141.3

# NeoForge
deps.neoforge=21.11.3-beta
neoforge_loader_version_range=[4,)

# Dependencies
deps.modmenu=17.0.0
deps.flow=2.2.0+1.21
deps.tia=1.2.3-fabric
# TODO: add TIA, Flow and whatever else that has fixes


