modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "GNU LGPL 3.0"

[[mods]]
modId = "${modId}"
version = "${modVersion}-mc${minecraftVersion}"
displayName = "${modName}"
authors = "${modAuthor}"
description = '''
${modDescription}
'''
logoFile = "assets/item_interactions_mod/icon.png"


[[dependencies.${ modId }]]
modId = "neoforge"
type = "required"
versionRange = "[21,)" # Should probably change this...
ordering = "NONE"
side = "CLIENT"

[[dependencies.${ modId }]]
modId = "minecraft"
type = "required"
versionRange = "[${minMinecraftVersion},)"
ordering = "NONE"
side = "CLIENT"


[[mixins]]
config = "item_interactions_mod.mixins.json"
